[dag] add DAGs for Uppsala kommun
02JanDal/osm-bjk pull request #42
Opened 2024-02-21 20:38 UTC by Prillan

Börjar med att ladda in datan. Ska försöka skapa lite enklare avvikelseberäkningar när jag får möjlighet senare!

Kommunen har bekräftat att datan är CC0, så det ska bara vara att köra på!

2024-02-21 20:49 UTC, 02JanDal requested changes
Vad underbart att det faktiskt fanns ett användningsbart API att gå emot!

Jag la till `07a-upstream-providers.sql` och `07b-upstream-datasets.sql` som du föreslog, så de behöver också uppdateras.

2024-02-21 20:49 UTC, 02JanDal commented on dags/uppsalakommun.py
> +            dataset=f"Uppsala kommun - {name}",
```suggestion
            dataset=name,
```

Det fullständiga sätts sedan ihop i frontend där det behövs

2024-02-21 20:49 UTC, 02JanDal commented on dags/uppsalakommun.py
> +            fetch=f"https://opendata.uppsala.se/api/download/v1/items/{dataset}/geojson?layers={layer}",
Tror vi kan våga oss på att gissa att `OBJECTID` är hyfsat beständig, skulle därför vara bra om den sätts som index på dataframen, då blir inladdningen lite smartare då den inte bara raderar allt befintligt:

```suggestion
            fetch=lambda: geopandas.read_file(f"https://opendata.uppsala.se/api/download/v1/items/{dataset}/geojson?layers={layer}").set_index("OBJECTID"),
```

2024-02-21 22:11 UTC, Prillan commented on dags/uppsalakommun.py
> +            dataset=f"Uppsala kommun - {name}",
japp japp, fixat!

2024-02-21 22:12 UTC, Prillan commented on dags/uppsalakommun.py
> +            fetch=f"https://opendata.uppsala.se/api/download/v1/items/{dataset}/geojson?layers={layer}",
Fixat, men behövde ändra typ på den, annars kraschade databasfrågan.

2024-02-21 22:13 UTC, Prillan commented
> Jag la till `07a-upstream-providers.sql` och `07b-upstream-datasets.sql` som du föreslog, så de behöver också uppdateras.

Fixat, men det va inte supersmidigt :sweat_smile:

2024-02-21 22:14 UTC, Prillan commented on dags/osm_bjk/fetch_dataframe_operator.py
> +                        val if (val := getattr(row, "bjk__updatedAt", pd.NaT)) is not pd.NaT else None,
Den bråkade lite här. Om du vill lösa det på något annat sätt går det såklart bra

2024-02-21 22:16 UTC, Prillan commented on dags/osm_bjk/fetch_dataframe_operator.py
> +                        val if (val := getattr(row, "bjk__updatedAt", pd.NaT)) is not pd.NaT else None,
(Med det menar jag att jag inte orkar komma på en bättre lösning just nu, men detta funkar)

2024-02-22 06:27 UTC, 02JanDal approved these changes
Toppen, mergar och deployar ikväll!

2024-02-25 17:00 UTC, merged

2024-02-25 17:01 UTC, 02JanDal commented
Några dagar senare så...